### ISSUE TITLE
Code for CAE v2?

### ISSUE THREAD

**Issue by Yikai-Wang** [Atten4Vis/CAE#2]
Hi there,

Thanks for your excellent work. I've noticed that you've recently released checkpoints for CAE v2. Could you please point me to the code for loading, training, and utilizing these checkpoints? Is the process the same as for the original CAE?

Additionally, I've observed that the provided checkpoints lack weights for the Regressor. Would it be possible to obtain pre-trained weights for the Regressor? 
Thank you!

**Comment by zhangxinyu-xyz** [comment]
> Hi there,
> 
> Thanks for your excellent work. I've noticed that you've recently released checkpoints for CAE v2. Could you please point me to the code for loading, training, and utilizing these checkpoints? Is the process the same as for the original CAE?
> 
> Additionally, I've observed that the provided checkpoints lack weights for the Regressor. Would it be possible to obtain pre-trained weights for the Regressor? Thank you!

Hi Yikai,

Very thanks for your interest.

We have released our CAE v2 code. Please refer to ``project/CAEv2/README.md''.

Since the downstream tasks do not use the weights of the Regressor, we only release the encoder's weights. It is useful for you? If yes, could you please send an email to us?

Best

**Comment by Yikai-Wang** [comment]
Thank you for your kind support.
